package flightscheduler;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

public class FlightScheduler extends javax.swing.JDialog {

    private String bookingDate, bookingFlight, bookingCust, bookingResult;
    private String addResult;
    private DefaultComboBoxModel m = ComboBoxModel(Customer.getCustomers());
    private String statusDate, statusFlight, statusResult;
    private String waitDate;
    private String newFName, newFResult;
    private int newFSeats;
    private String deleteFName, deleteFResult, deleteBResult;
    private String dayResult;
    private String cStatus;

    public FlightScheduler(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        StatusTab = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        newDay = new javax.swing.JTextField();
        DLabel = new javax.swing.JLabel();
        daySubmit = new javax.swing.JButton();
        AddDayResults = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nameSubmit = new javax.swing.JButton();
        newCust = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AddResults = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fNameField = new javax.swing.JTextField();
        fSeatsField = new javax.swing.JTextField();
        flightSubmit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        deleteflightSubmit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        FlightArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DateComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        FlightComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        bcBox = new javax.swing.JComboBox<>();
        CancelBooking = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        BookingResults = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        bStatus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FSBox = new javax.swing.JComboBox<>();
        DSBox = new javax.swing.JComboBox<>();
        DWBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        wStatus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusField = new javax.swing.JTextArea();
        custStatus = new javax.swing.JComboBox<>();
        customerStatus = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel1.setText("Flight Scheduler");

        DLabel.setText("Day:");

        daySubmit.setText("Submit");
        daySubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daySubmitActionPerformed(evt);
            }
        });

        AddDayResults.setEditable(false);
        AddDayResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDayResultsActionPerformed(evt);
            }
        });

        jLabel15.setText("(YYYY-MM-DD)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(DLabel)
                .addGap(65, 65, 65)
                .addComponent(newDay)
                .addGap(55, 55, 55)
                .addComponent(daySubmit)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(AddDayResults, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DLabel)
                    .addComponent(daySubmit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(AddDayResults, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        StatusTab.addTab("Add Day", jPanel4);

        nameSubmit.setText("Submit");
        nameSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSubmitActionPerformed(evt);
            }
        });

        newCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustActionPerformed(evt);
            }
        });

        jLabel5.setText("Customer's Name:");

        AddResults.setEditable(false);
        AddResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(newCust)
                .addGap(18, 18, 18)
                .addComponent(nameSubmit)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddResults, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(newCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSubmit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(AddResults, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        StatusTab.addTab("Add Customer", jPanel1);

        jLabel9.setText("Flight Name:");

        jLabel10.setText("Number of Seats:");

        fSeatsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSeatsFieldActionPerformed(evt);
            }
        });

        flightSubmit.setText("Submit");
        flightSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightSubmitActionPerformed(evt);
            }
        });

        jLabel11.setText("Add Flight");

        jLabel12.setText("Delete Flight");

        FComboBox.setModel(ComboBoxModel(Flights.getFlights()));
        FComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FComboBoxActionPerformed(evt);
            }
        });

        jLabel13.setText("Flight Name:");

        deleteflightSubmit.setText("Submit");
        deleteflightSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteflightSubmitActionPerformed(evt);
            }
        });

        FlightArea.setColumns(20);
        FlightArea.setRows(5);
        jScrollPane3.setViewportView(FlightArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fSeatsField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(99, 99, 99))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(flightSubmit)
                                        .addGap(89, 89, 89)))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(53, 53, 53))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(56, 56, 56)
                                        .addComponent(FComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(54, 54, 54))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(deleteflightSubmit)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSeatsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightSubmit)
                .addGap(46, 46, 46)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(deleteflightSubmit)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        StatusTab.addTab("Flight Manager", jPanel5);

        jLabel2.setText("Flight:");

        jLabel3.setText("Date:");

        DateComboBox.setModel(ComboBoxModel(Day.getDays()));
        DateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateComboBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Submit Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        FlightComboBox.setModel(ComboBoxModel(Flights.getFlights()));
        FlightComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Customer:");

        bcBox.setModel(m);
        bcBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcBoxActionPerformed(evt);
            }
        });

        CancelBooking.setText("Cancel Booking");
        CancelBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBookingActionPerformed(evt);
            }
        });

        BookingResults.setColumns(20);
        BookingResults.setRows(5);
        jScrollPane4.setViewportView(BookingResults);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelBooking))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(FlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bcBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(DateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(DateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bcBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(CancelBooking))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        StatusTab.addTab("Booking", jPanel2);

        bStatus.setText("Booking Status");
        bStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStatusActionPerformed(evt);
            }
        });

        jLabel6.setText("Flight");

        jLabel7.setText("Date");

        FSBox.setModel(ComboBoxModel(Flights.getFlights()));
        FSBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FSBoxActionPerformed(evt);
            }
        });

        DSBox.setModel(ComboBoxModel(Day.getDays()));
        DSBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSBoxActionPerformed(evt);
            }
        });

        DWBox.setModel(ComboBoxModel(Day.getDays()));
        DWBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DWBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Date");

        wStatus.setText("Waitlist Status");
        wStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wStatusActionPerformed(evt);
            }
        });

        statusField.setEditable(false);
        statusField.setColumns(20);
        statusField.setRows(5);
        jScrollPane2.setViewportView(statusField);

        custStatus.setModel(m);
        custStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custStatusActionPerformed(evt);
            }
        });

        customerStatus.setText("Customer Status");
        customerStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerStatusActionPerformed(evt);
            }
        });

        jLabel14.setText("Customer");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FSBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DSBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(11, 11, 11)))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(bStatus))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DWBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel8))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(customerStatus, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14)
                                                .addComponent(custStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(44, 44, 44)))
                                    .addComponent(wStatus))))
                        .addContainerGap(106, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FSBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DSBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bStatus)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DWBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wStatus)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );

        StatusTab.addTab("Status", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StatusTab))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StatusTab))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerStatusActionPerformed
        statusResult = Customer.Status(cStatus);
        statusField.setText(statusResult);
        statusField.setVisible(true);
        statusField.setEditable(false);
    }//GEN-LAST:event_customerStatusActionPerformed

    private void wStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wStatusActionPerformed
        statusResult = Waitlist.getWaitByDay(waitDate);
        statusField.setText(statusResult);
        statusField.setVisible(true);
        statusField.setEditable(false);
    }//GEN-LAST:event_wStatusActionPerformed

    private void DWBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DWBoxActionPerformed
        waitDate = String.valueOf(DWBox.getSelectedItem());
    }//GEN-LAST:event_DWBoxActionPerformed

    private void DSBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSBoxActionPerformed
        statusDate = String.valueOf(DSBox.getSelectedItem());
    }//GEN-LAST:event_DSBoxActionPerformed

    private void FSBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FSBoxActionPerformed
        statusFlight = String.valueOf(FSBox.getSelectedItem());
    }//GEN-LAST:event_FSBoxActionPerformed

    private void bStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStatusActionPerformed
        statusResult = Booking.bookingStatus(statusFlight, statusDate);
        statusField.setText(statusResult);
        statusField.setVisible(true);
        statusField.setEditable(false);
    }//GEN-LAST:event_bStatusActionPerformed

    private void CancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBookingActionPerformed
        deleteBResult = Booking.cancelBooking(bookingCust, bookingDate);
        BookingResults.setText(deleteBResult);
        BookingResults.setVisible(true);
        BookingResults.setEditable(false);
    }//GEN-LAST:event_CancelBookingActionPerformed

    private void bcBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcBoxActionPerformed
        bookingCust = String.valueOf(bcBox.getSelectedItem());
    }//GEN-LAST:event_bcBoxActionPerformed

    private void FlightComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightComboBoxActionPerformed
        bookingFlight = String.valueOf(FlightComboBox.getSelectedItem());
    }//GEN-LAST:event_FlightComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Booking.seats(bookingFlight, bookingDate))
        {
            bookingResult = Booking.book(bookingCust, bookingFlight, bookingDate);
            BookingResults.setText(bookingResult);
            BookingResults.setVisible(true);
            BookingResults.setEditable(false);
        }
        else
        {
            String x = "We are sorry but there are no \nseats availabale for that flight.\n";
            String y = Waitlist.waitlist(bookingCust, bookingFlight, bookingDate);
            bookingResult = x + y;
            BookingResults.setText(bookingResult);
            BookingResults.setVisible(true);
            BookingResults.setEditable(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateComboBoxActionPerformed
        bookingDate = String.valueOf(DateComboBox.getSelectedItem());
    }//GEN-LAST:event_DateComboBoxActionPerformed

    private void deleteflightSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteflightSubmitActionPerformed
        if(deleteFName != null)
        {
            deleteFResult = Flights.dropFlight(deleteFName);
            FlightArea.setText(deleteFResult);
            FlightArea.setVisible(true);
            FlightArea.setEditable(false);
            FComboBox.setModel(ComboBoxModel(Flights.getFlights()));
            FlightComboBox.setModel(ComboBoxModel(Flights.getFlights()));
            FSBox.setModel(ComboBoxModel(Flights.getFlights()));
        }
        else
        {
            newFResult = "Unable to remove flight to database.";
            FlightArea.setText(newFResult);
            FlightArea.setVisible(true);
            FlightArea.setEditable(false);
        }
    }//GEN-LAST:event_deleteflightSubmitActionPerformed

    private void FComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FComboBoxActionPerformed
        deleteFName = String.valueOf(FComboBox.getSelectedItem());
    }//GEN-LAST:event_FComboBoxActionPerformed

    private void flightSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightSubmitActionPerformed
        newFName = fNameField.getText();
        newFSeats = Integer.parseInt(fSeatsField.getText());
        if((newFName != null) && ((newFSeats > 0) || fSeatsField.getText() != null))
        {
            newFResult = Flights.addFlight(newFName, newFSeats);
            FlightArea.setText(newFResult);
            FlightArea.setVisible(true);
            FlightArea.setEditable(false);
            FComboBox.setModel(ComboBoxModel(Flights.getFlights()));
            FlightComboBox.setModel(ComboBoxModel(Flights.getFlights()));
            FSBox.setModel(ComboBoxModel(Flights.getFlights()));
        }
        else
        {
            newFResult = "Unable to add flight to database.";
            FlightArea.setText(newFResult);
            FlightArea.setVisible(true);
            FlightArea.setEditable(false);
        }
    }//GEN-LAST:event_flightSubmitActionPerformed

    private void AddResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddResultsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddResultsActionPerformed

    private void newCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustActionPerformed

    }//GEN-LAST:event_newCustActionPerformed

    private void nameSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSubmitActionPerformed
        if(newCust.getText() != null)
        {
            String name = String.valueOf(newCust.getText());
            addResult = Customer.addCustomer(name);
            AddResults.setText(addResult);
            AddResults.setVisible(true);
            AddResults.setEditable(false);
            m = ComboBoxModel(Customer.getCustomers());
            bcBox.setModel(m);
            custStatus.setModel(m);
        }
        else
        {
            AddResults.setText("No new customer was entered.");
            AddResults.setVisible(true);
            AddResults.setEditable(false);
        }
    }//GEN-LAST:event_nameSubmitActionPerformed

    private void AddDayResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDayResultsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddDayResultsActionPerformed

    private void daySubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daySubmitActionPerformed
       if(newDay.getText() != null)
       {
            String day = String.valueOf(newDay.getText());
            dayResult = Day.addDay(day);
            AddDayResults.setText(dayResult);
            AddDayResults.setVisible(true);
            AddDayResults.setEditable(false);
            DateComboBox.setModel(ComboBoxModel(Day.getDays()));
            DSBox.setModel(ComboBoxModel(Day.getDays()));
            DWBox.setModel(ComboBoxModel(Day.getDays()));
       }
       else
        {
            AddDayResults.setText("No new day was entered.");
            AddDayResults.setVisible(true);
            AddDayResults.setEditable(false);
        }
       
    }//GEN-LAST:event_daySubmitActionPerformed

    private void fSeatsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSeatsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fSeatsFieldActionPerformed

    private void custStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custStatusActionPerformed
        cStatus = String.valueOf(custStatus.getSelectedItem());
    }//GEN-LAST:event_custStatusActionPerformed

    public DefaultComboBoxModel ComboBoxModel(ArrayList < String> x)
    {
        String [] l = x.toArray(new String[x.size()]);
        DefaultComboBoxModel model = new DefaultComboBoxModel( l );
        return model;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            FlightScheduler dialog = new FlightScheduler(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddDayResults;
    private javax.swing.JTextField AddResults;
    private javax.swing.JTextArea BookingResults;
    private javax.swing.JButton CancelBooking;
    private javax.swing.JLabel DLabel;
    private javax.swing.JComboBox<String> DSBox;
    private javax.swing.JComboBox<String> DWBox;
    private javax.swing.JComboBox<String> DateComboBox;
    private javax.swing.JComboBox<String> FComboBox;
    private javax.swing.JComboBox<String> FSBox;
    private javax.swing.JTextArea FlightArea;
    private javax.swing.JComboBox<String> FlightComboBox;
    private javax.swing.JTabbedPane StatusTab;
    private javax.swing.JButton bStatus;
    private javax.swing.JComboBox<String> bcBox;
    private javax.swing.JComboBox<String> custStatus;
    private javax.swing.JButton customerStatus;
    private javax.swing.JButton daySubmit;
    private javax.swing.JButton deleteflightSubmit;
    private javax.swing.JTextField fNameField;
    private javax.swing.JTextField fSeatsField;
    private javax.swing.JButton flightSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton nameSubmit;
    private javax.swing.JTextField newCust;
    private javax.swing.JTextField newDay;
    private javax.swing.JTextArea statusField;
    private javax.swing.JButton wStatus;
    // End of variables declaration//GEN-END:variables
}
